spring:
  mail:
    host: smtp.gmail.com
    username: alixrad77@gmail.com
    password: mlevoxzchtrhlnie
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true